"""Give everything in the catalogue an image, and attach it.

Separate from `seed.py` and idempotent: it only fills gaps. A product that
already has real photography is left alone, so running this after somebody has
uploaded their own work cannot overwrite it.

    python -m scripts.seed_media             # stand-in photographs (default)
    python -m scripts.seed_media --drawings  # locally drawn SVG artwork
    python -m scripts.seed_media --replace   # redo the stand-ins it owns

TWO SOURCES, AND WHY BOTH EXIST

    Photographs are hotlinked stand-ins from Unsplash (see `photos.py`). The
    shop is a furniture shop, and line art on every card reads as a wireframe
    to anyone being shown it.

    Drawings are SVGs generated by `artwork.py`, in the storefront's own
    palette. They cost no network, so the catalogue still renders on a train,
    in CI, or behind an egress proxy - which is exactly where a page full of
    remote URLs becomes a page full of broken images.

    Neither is a photograph of a real product. Both are replaced, piece by
    piece, as real photography arrives through the dashboard, with no code
    change.

Switching sources needs no flag beyond the source itself: a run replaces the
stand-ins that came from the *other* source, so `--drawings` and back again
both do what they say. `--replace` additionally redoes stand-ins from the same
source. Neither ever touches an upload.
"""
import asyncio
import sys

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.database import SessionLocal, engine
from app.models.catalog import Category, Collection, Product, ProductImage, Room
from app.models.content import Banner
from app.providers.storage import get_storage
from scripts import artwork, photos

# Anything under this prefix was drawn by this script and may be regenerated.
GENERATED = "generated"

# Remote placeholder services. A URL pointing at one is not photography by any
# definition - it is a stand-in - so it is replaceable too. `photos.HOST` is
# here for the same reason: the shop's own stand-ins must never be mistaken
# for somebody's uploaded work.
PLACEHOLDER_HOSTS = (
    photos.HOST,
    "picsum.photos",
    "placehold.co",
    "placekitten.com",
    "via.placeholder.com",
)


async def store(svg: str, name: str) -> str:
    return await get_storage().save(
        data=svg.encode("utf-8"),
        filename=f"{name}.svg",
        content_type="image/svg+xml",
        folder=GENERATED,
    )


def is_generated(url: str | None) -> bool:
    """True when this script may overwrite the image.

    Covers what it drew itself, and remote stand-ins. Never a real upload -
    those live under the storage provider's own folders and are somebody's
    work.
    """
    if not url:
        return False
    return f"/{GENERATED}/" in url or any(host in url for host in PLACEHOLDER_HOSTS)


def is_current_source(url: str | None, drawings: bool) -> bool:
    """True when this stand-in already came from the source being asked for.

    What makes a second run a no-op, and what makes switching sources replace
    rather than pile up.
    """
    if not url:
        return False
    return f"/{GENERATED}/" in url if drawings else photos.is_photo(url)


async def seed_products(session: AsyncSession, replace: bool, drawings: bool) -> int:
    products = (
        await session.execute(select(Product).options(selectinload(Product.images)))
    ).scalars().all()

    touched = 0
    for product in products:
        uploaded = [i for i in product.images if not is_generated(i.url)]
        replaceable = [i for i in product.images if is_generated(i.url)]
        current = [i for i in replaceable if is_current_source(i.url, drawings)]

        # A product with real photography is finished. Adding a stand-in beside
        # a photograph would look like a mistake in the gallery.
        if uploaded:
            continue
        # Already done from this source, and not being asked to redo it.
        if current and not replace:
            continue
        for image in replaceable:
            await session.delete(image)

        # Four framings, in the order the gallery shows them. Studio first
        # because that is what the card uses.
        shots = {} if drawings else photos.product_images(product.name)
        for position, kind in enumerate(("studio", "lifestyle", "detail", "dimension")):
            # `dimension` is a measured drawing whatever the source: it is
            # information about this product, and no stock library holds one.
            url = shots.get(kind) or await store(
                artwork.product_image(product.name, kind),
                f"{product.slug}-{kind}",
            )
            session.add(
                ProductImage(
                    product_id=product.id,
                    url=url,
                    alt_text=_alt(product.name, kind, drawings),
                    kind=kind,
                    position=position,
                )
            )
        touched += 1

    return touched


def _alt(name: str, kind: str, drawings: bool) -> str:
    """Alt text that says what the image shows, per framing.

    Four images all described as "photograph of X" is four identical
    announcements to a screen-reader user scrolling a gallery.

    A stand-in photograph says so. It shows a sofa, but not *this* sofa, and
    the one reader who depends entirely on this sentence is the one who would
    otherwise be told a stock room is the product they are buying.
    """
    if kind == "dimension" or drawings:
        return {
            "studio": f"{name}, shown against a plain background",
            "lifestyle": f"{name} in a furnished room",
            "detail": f"Close view of the joinery and material on {name}",
            "dimension": f"Measured drawing of {name} showing its width and height",
        }[kind]

    return {
        "studio": f"Stand-in photograph for {name}: a similar piece against a plain background",
        "lifestyle": f"Stand-in photograph for {name}: a similar piece in a furnished room",
        "detail": f"Stand-in photograph for {name}: a close view of a similar material",
    }[kind]


async def seed_taxonomy(session: AsyncSession, replace: bool, drawings: bool) -> dict[str, int]:
    counts = {"categories": 0, "rooms": 0, "collections": 0}

    for model, key, folder in (
        (Category, "categories", "category"),
        (Room, "rooms", "room"),
        (Collection, "collections", "collection"),
    ):
        rows = (await session.execute(select(model))).scalars().all()
        for row in rows:
            done = is_current_source(row.image_url, drawings)
            if row.image_url and not (is_generated(row.image_url) and (replace or not done)):
                continue
            row.image_url = (
                await store(artwork.taxonomy_image(row.name), f"{folder}-{row.slug}")
                if drawings
                else photos.taxonomy_image(row.name)
            )
            counts[key] += 1

    return counts


async def seed_banners(session: AsyncSession, replace: bool, drawings: bool) -> int:
    banners = (await session.execute(select(Banner))).scalars().all()
    touched = 0
    for banner in banners:
        done = is_current_source(banner.image_url, drawings)
        needs = not banner.image_url or is_generated(banner.image_url) and (replace or not done)
        if not needs:
            continue

        if drawings:
            banner.image_url = await store(artwork.banner_image(wide=True), "banner-hero-wide")
            # A 21:9 hero crops into nonsense on a phone, so the mobile asset is
            # a different drawing rather than the same one squeezed.
            banner.mobile_image_url = await store(
                artwork.banner_image(wide=False), "banner-hero-tall"
            )
        else:
            banner.image_url, banner.mobile_image_url = photos.banner_images()
        touched += 1
    return touched


async def main() -> None:
    replace = "--replace" in sys.argv
    drawings = "--drawings" in sys.argv

    async with SessionLocal() as session:
        products = await seed_products(session, replace, drawings)
        taxonomy = await seed_taxonomy(session, replace, drawings)
        banners = await seed_banners(session, replace, drawings)
        await session.commit()

    total = products * 4
    print(f"  source: {'drawn artwork' if drawings else 'stand-in photographs'}")
    print(f"  {total} product images across {products} product(s)")
    print(f"  {taxonomy['categories']} category, {taxonomy['rooms']} room, "
          f"{taxonomy['collections']} collection tiles")
    print(f"  {banners} banner(s)")
    if not any((products, banners, *taxonomy.values())):
        print("  everything already has artwork — nothing to do")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
